### ISSUE TITLE
Custom login page with local bg image

### ISSUE THREAD

**Issue by kikearciniegas** [lewazo/boreale#19]
Sorry if this is an obvious sort of question, my knowledge is pretty limited on this... How do you reference in the .css a local background image? I tried just leaving the name of the file `url("bgimage.jpg");` as it is in the same folder, next to the custom login.css and login.html, but the image is not getting picked up.

Also tried using the full path of the data folder `url("/opt/app/data/bgimage.jpg");` but the same thing happens, it is not picked up by the custom .css.

Any help is greatly appreciated.

**Comment by lewazo** [comment]
You are right, for now static assets are not served, so local images can't be loaded. I'm not sure if we can make this work since, when not authenticated, Traefik forwards all requests to `/`, so that would include other resources such as pages, styles, fonts and images.

The reason why the css file works is because it is being added directly to the HTML response, as part of the same page in a `<style>` tag.

I'll try and come up with a solution, but I'm not sure if this is doable right now.

**Comment by kikearciniegas** [comment]
Got it.. Thanks for the quick answer.
